version: '3.1'

services:
  agent1:
    image: balabit/syslog-ng:3.7
    hostname: agent1
    volumes:
      - "./syslog-ng/agent/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
    ports:
      - 602:602
    depends_on:
      - central1

  central1:
    image: balabit/syslog-ng:3.7
    hostname: central1
    volumes:
      - "./syslog-ng/central/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      - "./logs/:/tmp/"
    ports:
      - 603:603

  loggen1:
    image: log-generator-image
    hostname: loggen1
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:602"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    depends_on:
      - agent1

#  loggen2:
#    image: log-generator-image
#    hostname: loggen2
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://127.0.0.1:602"
#        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
#    depends_on:
#      - agent1

networks:
  default:
    external:
      name: logs-network