version: '3.1'

services:
  agent1:
    image: yakud/rsyslog
    hostname: agent1
    volumes:
      - "./rsyslog/agent/agent.conf:/etc/rsyslog.d/agent.conf"
    ports:
      - 1514:1514
    depends_on:
      - central1

  central1:
    image: yakud/rsyslog
    hostname: central1
    volumes:
      - "./rsyslog/central/central.conf:/etc/rsyslog.d/central.conf"
      - "./logs/:/tmp/"
    ports:
      - 20514:20514

  loggen1:
    image: log-generator-image
    hostname: loggen1
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    depends_on:
      - agent1

  loggen2:
    image: log-generator-image
    hostname: loggen2
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    depends_on:
      - agent1

  loggen3:
    image: log-generator-image
    hostname: loggen3
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    depends_on:
      - agent1

  loggen4:
    image: log-generator-image
    hostname: loggen4
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    depends_on:
      - agent1

networks:
  default:
    external:
      name: logs-network